In [10]:
'''Document ranking

         Document1   Document2  Document3
Keyword1  0.25       0.53       0.75
Keyword2  0.73       0.50       0.23

'''
import numpy as np
A = np.matrix([[0.25, 0.53, 0.75], [0.73, 0.50, 0.23]])
U, s, V = np.linalg.svd(A)

print("Singular Value Decomposition:\n s:\n",s)
print("V:\n",V)
print("U:\n",U)

Singular Value Decomposition:
 s:
 [ 1.221409    0.49986004]
V:
 [[-0.55927708 -0.59654757 -0.57562153]
 [ 0.71788087 -0.00128553 -0.69616478]
 [ 0.41455543 -0.80257669  0.42896905]]
U:
 [[-0.72678819 -0.68686165]
 [-0.68686165  0.72678819]]


In [11]:
k = 1  #ignoring smaller values of the two singular values 
new_A = U[:, :k] * np.diag(s[:k]) * V[:k, :]
print("Reconstructed F ignoring smaller of the two singular values:\n",new_A)

Reconstructed F ignoring smaller of the two singular values:
 [[ 0.49647341  0.52955863  0.51098248]
 [ 0.46919935  0.50046702  0.48291136]]


In [12]:
new_u=U[:, :k]
new_s=np.diag(s[:k])
new_vt=V[:k, :]
Q = np.matrix([[1],[0]])
print("Query transpose:\n",Q.T)
print("new u:\n",new_u)
print("new s:\n",new_s)
print("new v:'\n",new_vt)

Query transpose:
 [[1 0]]
new u:
 [[-0.72678819]
 [-0.68686165]]
new s:
 [[ 1.221409]]
new v:'
 [[-0.55927708 -0.59654757 -0.57562153]]


In [13]:
#LSI space representation
lowDimensionalQueryVector = Q.T * new_u * np.linalg.inv(new_s)
print("low Dimensional Query Represenation:\n",lowDimensionalQueryVector)
print("low Dimensional Document Represenation:\n",new_vt)

low Dimensional Query Represenation:
 [[-0.5950408]]
low Dimensional Document Represenation:
 [[-0.55927708 -0.59654757 -0.57562153]]


In [14]:
from sklearn.metrics.pairwise import cosine_similarity
cos_similarity=cosine_similarity(lowDimensionalQueryVector, new_vt.T)
print("Cosine Similarity:")
print(cos_similarity)   #ranks of all documents are same for k=1

Cosine Similarity:
[[ 1.  1.  1.]]
